name: Auto approve dependabot

on:
  pull_request:
    types:
      - opened
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: merge PR
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
        run: gh pr list | while read line; do gh pr merge `echo $line|awk '{print $1}'` -m; done